

project_root: ${hydra:runtime.cwd} # or use hydra.utils.get_original_cwd() if needed

# Where to load the model & preprocessors from
local:
  export_dir: model_export/latest  # resolved relative to project root

load_from: mlflow                  # or "mlflow"

mlflow:
  model_name: TabularMultiTargetRegressor
  version: latest
  alias: champion     # ← this field exists

input:
  path: data/processed/model_df.parquet # 
  format: auto                     # auto, csv, parquet

output:
  path: predictions.csv
  include_index: true
  columns_prefix: pred_

target_cols: [breast, lung_and_bronchus, melanoma_of_the_skin]

# target_cols: 
#   - breast
#   - lung_and_bronchus
#   - melanoma_of_the_skin

num_workers: 0
batch_size: 256
device: null                       # null = auto (cuda > mps > cpu)